FROM node:18
WORKDIR /usr/src/app/quasar-project
RUN npm i -g @quasar/cli
# RUN quasar dev

# FROM node:18

# WORKDIR /usr/src/app

# RUN npm i -g @quasar/cli

# after starting container run "npm init quasar"
# then to down container and rewrite this Dockerfile:
      
#
# PS: you can remove "RUN quasar dev" and write this command to the docker-compose.yml