name: CI for ironore

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cicd-for-ironore:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Say Hello
      run: echo "Hello, GitHub Actions! This is my first workflow!"
      
    - name: Show date
      run: date
